# Configuration for update-docs - https://github.com/behaviorbot/update-docs

# Comment to be posted to on PRs that don't update the changelog
updateDocsComment: >
  Thanks for submitting this pull request! The maintainers of this repository would appreciate if you could update the **CHANGELOG.md** based on your changes.

updateDocsWhiteList:
  - documentation

updateDocsTargetFiles:
  - CHANGELOG.md
